### ISSUE TITLE
ПЫЩПЫЩ! слишком костыльная проверка, как мне кажется

### ISSUE THREAD

**Issue by heroboec** [missvalentinep/MBR_parser#1]
https://github.com/missvalentinep/MBR_parser/blob/d9c949261932d9ceaffd41aa19bf82fa7aaa4de4/main.c#L133
Вместо того, чтобы проверять 4 байта подряд в массиве нужно указатель на первый элемент привести к указателю на что-то четырехбайтовое например uint, разыменовать,  а потом проверить на равенство с 0xffffffff это будет чуть более красиво. Кроме того первые 4 байта заголовка атрибута описывают его тип и нет ни одного типа в коде которого фигурировал бы бай 0xff. Так что тут возникает вопрос нужно ли тебе на границе атрибутов проверять целых 4 байта?

**Comment by missvalentinep** [comment]
Теперь программа считывает файловые записи с MFT (нам известно начало MFT, и там каждая запись занимает 1024 байта), так что костыльная проверка была убрана.
