### ISSUE TITLE
неправильный выбор константы для чтения образа

### ISSUE THREAD

**Issue by heroboec** [missvalentinep/MBR_parser#2]
https://github.com/missvalentinep/MBR_parser/blob/d9c949261932d9ceaffd41aa19bf82fa7aaa4de4/main.c#L107
Если коротко:
1) 1500000 это довольно большой кусок для единовременного чтения но с этим еще можно смириться и жить
2) чтобы читать кусками меньше, тебе надо вспомнить про функцию seek которая даст тебе возможность переместиться в нужное место файла и читать прям оттуда
3) после того как ты прочитала эти 1500000 байт ты закрываешь файл будто он тебе не пригодится больше. Пригодится ! Как минимум для того чтобы получить данные одного из файлов, они спрятаны намного дальше в образе.
Файл нужно открыть вначале, соблюдать умеренность в чтении больших кусков за 1 заход (т.к. они будут занимать память программы), не закрывать файл образа до отработки всей твоей программы, вдруг что-то еще понадобится.

**Comment by missvalentinep** [comment]
Теперь программа читает первые 512 байт, затем ищет в них расположение MFT и считывает ее записи отдельно, т.е. максимальный размер буфера - 1024
